# animal_data.py

ANIMAL_CATEGORIES = {
    "mammals": {
        "name": {"en": "Mammals", "zh": "哺乳动物", "ko": "포유류"},
        "description": {
            "en": "Warm-blooded vertebrates with hair and milk production.",
            "zh": "温血、体表有毛、哺乳的脊椎动物。",
            "ko": "털이 있고 젖을 먹여 키우는 온혈 척추동물."
        },
        "icon": "🦁",
    },
    "birds": {
        "name": {"en": "Birds", "zh": "鸟类", "ko": "조류"},
        "description": {
            "en": "Feathered vertebrates, many adapted for flight.",
            "zh": "有羽毛的脊椎动物，许多能飞行。",
            "ko": "깃털이 있는 척추동물로 많은 종이 비행에 적응."
        },
        "icon": "🦅",
    },
    "reptiles": {
        "name": {"en": "Reptiles", "zh": "爬行动物", "ko": "파충류"},
        "description": {
            "en": "Cold-blooded vertebrates with scales, mostly egg-laying.",
            "zh": "冷血、有鳞片，多为卵生的脊椎动物。",
            "ko": "비늘이 있고 변온인 척추동물, 대부분 알을 낳음."
        },
        "icon": "🐍",
    },
    "amphibians": {
        "name": {"en": "Amphibians", "zh": "两栖动物", "ko": "양서류"},
        "description": {
            "en": "Animals that live both in water and on land with metamorphosis.",
            "zh": "水陆两栖、常有变态发育。",
            "ko": "물과 육지에서 모두 살며 변태 과정을 겪는 동물."
        },
        "icon": "🐸",
    },
    "fish": {
        "name": {"en": "Fish", "zh": "鱼类", "ko": "어류"},
        "description": {
            "en": "Aquatic vertebrates that breathe mainly through gills.",
            "zh": "水生、用鳃呼吸的脊椎动物。",
            "ko": "물속에서 살며 주로 아가미로 호흡."
        },
        "icon": "🐟",
    },
    "insects": {
        "name": {"en": "Insects", "zh": "昆虫", "ko": "곤충"},
        "description": {
            "en": "Six-legged arthropods with exoskeletons.",
            "zh": "六足、有外骨骼的节肢动物。",
            "ko": "외골격을 가진 6개의 다리를 지닌 절지동물."
        },
        "icon": "🦋",
    },
}

# 为了不让文件过于臃肿：每种动物用较短科普字段
# 你之后可以继续扩写 facts / habitat 等内容

ANIMALS_DATA = {
    # ===================== Mammals (12) =====================
    "giant_panda": {
        "category": "mammals",
        "name": {"en": "Giant Panda", "zh": "大熊猫", "ko": "자이언트 판다"},
        "scientific_name": "Ailuropoda melanoleuca",
        "image": "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200",
        "summary": {
            "en": "A bamboo-specialist bear native to China.",
            "zh": "中国特有的以竹子为主食的熊科动物。",
            "ko": "중국 고유의 대나무를 주식으로 하는 곰."
        },
        "habitat": {
            "en": "Temperate mountain forests",
            "zh": "温带山地森林",
            "ko": "온대 산악 숲"
        },
        "facts": {
            "en": ["Uses a 'pseudo-thumb' to grip bamboo."],
            "zh": ["利用“伪拇指”抓握竹子。"],
            "ko": ["'가짜 엄지'로 대나무를 잡는다."]
        },
    },
    "tiger": {
        "category": "mammals",
        "name": {"en": "Tiger", "zh": "老虎", "ko": "호랑이"},
        "scientific_name": "Panthera tigris",
        "image": "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=1200",
        "summary": {
            "en": "The largest cat species and an apex predator in Asia.",
            "zh": "亚洲顶级掠食者，最大的猫科动物。",
            "ko": "아시아의 최상위 포식자이자 가장 큰 고양잇과."
        },
        "habitat": {"en": "Forests and grasslands", "zh": "森林与草原", "ko": "숲과 초원"},
        "facts": {"en": ["Each stripe pattern is unique."], "zh": ["条纹像指纹一样独特。"], "ko": ["줄무늬는 지문처럼 개체마다 다르다."]},
    },
    "african_elephant": {
        "category": "mammals",
        "name": {"en": "African Elephant", "zh": "非洲象", "ko": "아프리카 코끼리"},
        "scientific_name": "Loxodonta africana",
        "image": "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=1200",
        "summary": {
            "en": "The largest land mammal with complex social behavior.",
            "zh": "陆地最大哺乳动物，社会性强。",
            "ko": "육지에서 가장 큰 포유류로 사회성이 높다."
        },
        "habitat": {"en": "Savannas and forests", "zh": "草原与森林", "ko": "사바나와 숲"},
        "facts": {"en": ["Gestation lasts about 22 months."], "zh": ["妊娠期约22个月。"], "ko": ["임신 기간이 약 22개월이다."]},
    },
    "lion": {
        "category": "mammals",
        "name": {"en": "Lion", "zh": "狮子", "ko": "사자"},
        "scientific_name": "Panthera leo",
        "image": "https://images.unsplash.com/photo-1546182990-0f9f7f4b1d6b?w=1200",
        "summary": {"en": "A social big cat living in prides.", "zh": "群居生活的猫科猛兽。", "ko": "무리를 이루어 사는 대형 고양잇과."},
        "habitat": {"en": "African savannas", "zh": "非洲草原", "ko": "아프리카 사바나"},
        "facts": {"en": ["Females do most hunting."], "zh": ["雌狮负责主要狩猎。"], "ko": ["암컷이 주로 사냥한다."]},
    },
    "polar_bear": {
        "category": "mammals",
        "name": {"en": "Polar Bear", "zh": "北极熊", "ko": "북극곰"},
        "scientific_name": "Ursus maritimus",
        "image": "https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=1200",
        "summary": {"en": "Arctic marine bear adapted to sea ice life.", "zh": "适应海冰环境的北极顶级捕食者。", "ko": "해빙 환경에 적응한 북극의 최상위 포식자."},
        "habitat": {"en": "Arctic sea ice", "zh": "北极海冰", "ko": "북극 해빙"},
        "facts": {"en": ["Excellent long-distance swimmers."], "zh": ["远距离游泳能力强。"], "ko": ["장거리 수영에 능하다."]},
    },
    "wolf": {
        "category": "mammals",
        "name": {"en": "Gray Wolf", "zh": "灰狼", "ko": "회색늑대"},
        "scientific_name": "Canis lupus",
        "image": "https://images.unsplash.com/photo-1546182990-2f9c5d0b2e86?w=1200",
        "summary": {"en": "Highly social canid living in packs.", "zh": "高度社会化的犬科动物。", "ko": "무리를 이루는 사회적 개과 동물."},
        "habitat": {"en": "Forests, tundra, mountains", "zh": "森林、苔原、山地", "ko": "숲·툰드라·산지"},
        "facts": {"en": ["Communicates with howls."], "zh": ["用嚎叫交流。"], "ko": ["울음소리로 의사소통한다."]},
    },
    "red_fox": {
        "category": "mammals",
        "name": {"en": "Red Fox", "zh": "赤狐", "ko": "붉은여우"},
        "scientific_name": "Vulpes vulpes",
        "image": "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=1200",
        "summary": {"en": "A widespread and adaptable fox species.", "zh": "分布广、适应力强的狐狸。", "ko": "분포가 넓고 적응력이 뛰어난 여우."},
        "habitat": {"en": "Forests, fields, cities", "zh": "森林、田野、城市", "ko": "숲·초지·도시"},
        "facts": {"en": ["Can hear small prey underground."], "zh": ["能听到地下小动物的动静。"], "ko": ["땅속 작은 먹이 소리를 들을 수 있다."]},
    },
    "koala": {
        "category": "mammals",
        "name": {"en": "Koala", "zh": "考拉", "ko": "코알라"},
        "scientific_name": "Phascolarctos cinereus",
        "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200",
        "summary": {"en": "Eucalyptus-eating marsupial of Australia.", "zh": "澳大利亚的桉树专食有袋类。", "ko": "호주의 유칼립투스를 먹는 유대류."},
        "habitat": {"en": "Eucalyptus forests", "zh": "桉树林", "ko": "유칼립투스 숲"},
        "facts": {"en": ["Sleeps up to 20 hours a day."], "zh": ["每天可睡20小时。"], "ko": ["하루에 최대 20시간 잔다."]},
    },
    "kangaroo": {
        "category": "mammals",
        "name": {"en": "Red Kangaroo", "zh": "红大袋鼠", "ko": "붉은캥거루"},
        "scientific_name": "Osphranter rufus",
        "image": "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=1200",
        "summary": {"en": "Largest marsupial known for powerful hopping.", "zh": "以强劲跳跃著称的最大有袋类。", "ko": "강력한 점프로 유명한 가장 큰 유대류."},
        "habitat": {"en": "Australian arid regions", "zh": "澳大利亚干旱地区", "ko": "호주 건조 지역"},
        "facts": {"en": ["Can jump over 8 meters in one bound."], "zh": ["一次可跳超过8米。"], "ko": ["한 번에 8m 이상 뛸 수 있다."]},
    },
    "dolphin": {
        "category": "mammals",
        "name": {"en": "Bottlenose Dolphin", "zh": "宽吻海豚", "ko": "큰돌고래"},
        "scientific_name": "Tursiops truncatus",
        "image": "https://images.unsplash.com/photo-1609788071657-2f9c5d74b1b1?w=1200",
        "summary": {"en": "Intelligent marine mammal using echolocation.", "zh": "会用回声定位的聪明海洋哺乳动物。", "ko": "반향정위를 사용하는 지능 높은 해양 포유류."},
        "habitat": {"en": "Coastal oceans", "zh": "近海", "ko": "연안 해역"},
        "facts": {"en": ["Has signature whistles."], "zh": ["有“专属口哨声”。"], "ko": ["개체별 '고유 휘파람'이 있다."]},
    },
    "bat": {
        "category": "mammals",
        "name": {"en": "Fruit Bat", "zh": "果蝠", "ko": "과일박쥐"},
        "scientific_name": "Pteropodidae",
        "image": "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=1200",
        "summary": {"en": "Important pollinators and seed dispersers.", "zh": "重要的传粉者与种子传播者。", "ko": "중요한 수분 매개자이자 씨앗 확산자."},
        "habitat": {"en": "Tropical forests", "zh": "热带森林", "ko": "열대 숲"},
        "facts": {"en": ["Many rely on smell and sight."], "zh": ["很多依赖嗅觉和视觉。"], "ko": ["많은 종이 후각과 시각에 의존한다."]},
    },
    "platypus": {
        "category": "mammals",
        "name": {"en": "Platypus", "zh": "鸭嘴兽", "ko": "오리너구리"},
        "scientific_name": "Ornithorhynchus anatinus",
        "image": "https://images.unsplash.com/photo-1610465299993-8d3f8d16f5f7?w=1200",
        "summary": {"en": "An egg-laying mammal with a duck-like bill.", "zh": "会下蛋、嘴像鸭子的奇特哺乳动物。", "ko": "알을 낳고 오리 같은 부리를 가진 독특한 포유류."},
        "habitat": {"en": "Australian rivers", "zh": "澳大利亚河流", "ko": "호주 강"},
        "facts": {"en": ["Males have venomous spurs."], "zh": ["雄性有毒刺。"], "ko": ["수컷은 독이 있는 발톱 돌기가 있다."]},
    },

    # ===================== Birds (12) =====================
    "golden_eagle": {
        "category": "birds",
        "name": {"en": "Golden Eagle", "zh": "金雕", "ko": "검독수리"},
        "scientific_name": "Aquila chrysaetos",
        "image": "https://images.unsplash.com/photo-1611689342806-0863700ce1e4?w=1200",
        "summary": {"en": "A powerful raptor of mountains and open lands.", "zh": "山地与开阔地带的强大猛禽。", "ko": "산지와 개활지의 강력한 맹금."},
        "habitat": {"en": "Mountains and plateaus", "zh": "山地与高原", "ko": "산·고원"},
        "facts": {"en": ["Exceptional eyesight."], "zh": ["视力极佳。"], "ko": ["시력이 매우 뛰어나다."]},
    },
    "emperor_penguin": {
        "category": "birds",
        "name": {"en": "Emperor Penguin", "zh": "帝企鹅", "ko": "황제펭귄"},
        "scientific_name": "Aptenodytes forsteri",
        "image": "https://images.unsplash.com/photo-1551986782-d0169b3f8fa7?w=1200",
        "summary": {"en": "Largest penguin adapted to Antarctic winters.", "zh": "适应南极严寒的最大企鹅。", "ko": "남극 혹한에 적응한 가장 큰 펭귄."},
        "habitat": {"en": "Antarctic ice edges", "zh": "南极冰缘", "ko": "남극 빙연"},
        "facts": {"en": ["Males incubate eggs in winter."], "zh": ["雄企鹅在冬季孵蛋。"], "ko": ["수컷이 겨울에 알을 품는다."]},
    },
    "barn_owl": {
        "category": "birds",
        "name": {"en": "Barn Owl", "zh": "仓鸮", "ko": "올빼미(바른올빼미)"},
        "scientific_name": "Tyto alba",
        "image": "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=1200",
        "summary": {"en": "A silent nocturnal hunter with heart-shaped face.", "zh": "脸盘心形、夜间无声猎手。", "ko": "하트 모양 얼굴을 가진 조용한 야행성 사냥꾼."},
        "habitat": {"en": "Farms and grasslands", "zh": "农田与草地", "ko": "농경지·초지"},
        "facts": {"en": ["Hunts mainly rodents."], "zh": ["主要捕食鼠类。"], "ko": ["주로 설치류를 사냥한다."]},
    },
    "peacock": {
        "category": "birds",
        "name": {"en": "Indian Peafowl", "zh": "蓝孔雀", "ko": "인도공작"},
        "scientific_name": "Pavo cristatus",
        "image": "https://images.unsplash.com/photo-1544025162-d76694265947?w=1200",
        "summary": {"en": "Known for dazzling tail displays.", "zh": "以绚丽开屏著称。", "ko": "화려한 꼬리 과시로 유명."},
        "habitat": {"en": "Open forests", "zh": "疏林与开阔地", "ko": "개방 숲"},
        "facts": {"en": ["Tail feathers used in courtship."], "zh": ["尾羽用于求偶。"], "ko": ["꼬리 깃털은 구애에 사용된다."]},
    },
    "flamingo": {
        "category": "birds",
        "name": {"en": "Greater Flamingo", "zh": "大红鹳", "ko": "큰홍학"},
        "scientific_name": "Phoenicopterus roseus",
        "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200",
        "summary": {"en": "Pink wading bird feeding on small aquatic life.", "zh": "以滤食小型水生生物为生的粉色涉禽。", "ko": "작은 수생 생물을 걸러 먹는 분홍색 섭금류."},
        "habitat": {"en": "Saline lakes", "zh": "盐湖与浅水湖", "ko": "염호"},
        "facts": {"en": ["Color comes from diet pigments."], "zh": ["颜色来自食物色素。"], "ko": ["색은 먹이의 색소에서 온다."]},
    },
    "hummingbird": {
        "category": "birds",
        "name": {"en": "Hummingbird", "zh": "蜂鸟", "ko": "벌새"},
        "scientific_name": "Trochilidae",
        "image": "https://images.unsplash.com/photo-1465101162946-4377e57745c3?w=1200",
        "summary": {"en": "Tiny birds capable of hovering flight.", "zh": "能悬停飞行的迷你鸟类。", "ko": "정지비행이 가능한 작은 새."},
        "habitat": {"en": "Americas' gardens and forests", "zh": "美洲花园与森林", "ko": "아메리카의 숲·정원"},
        "facts": {"en": ["Wings can beat over 50 times per second."], "zh": ["翅膀每秒可振动50次以上。"], "ko": ["날개를 초당 50번 이상 퍼덕인다."]},
    },
    "albatross": {
        "category": "birds",
        "name": {"en": "Wandering Albatross", "zh": "漂泊信天翁", "ko": "떠돌이알바트로스"},
        "scientific_name": "Diomedea exulans",
        "image": "https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=1200",
        "summary": {"en": "Seabird with the greatest wingspan among birds.", "zh": "翼展最大的海鸟之一。", "ko": "새 중 가장 긴 날개폭을 가진 바닷새."},
        "habitat": {"en": "Southern Ocean", "zh": "南大洋", "ko": "남극해"},
        "facts": {"en": ["Can glide for hours with little flapping."], "zh": ["可长时间滑翔。"], "ko": ["오래 활공할 수 있다."]},
    },
    "kingfisher": {
        "category": "birds",
        "name": {"en": "Common Kingfisher", "zh": "普通翠鸟", "ko": "물총새"},
        "scientific_name": "Alcedo atthis",
        "image": "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=1200",
        "summary": {"en": "Small bright bird diving for fish.", "zh": "色彩鲜艳、俯冲捕鱼。", "ko": "선명한 색의 작은 새로 물고기를 급강하해 잡는다."},
        "habitat": {"en": "Rivers and lakes", "zh": "河流湖泊", "ko": "강·호수"},
        "facts": {"en": ["Builds nests in riverbanks."], "zh": ["在河岸打洞筑巢。"], "ko": ["강둑에 굴을 파서 둥지를 만든다."]},
    },
    "swan": {
        "category": "birds",
        "name": {"en": "Mute Swan", "zh": "疣鼻天鹅", "ko": "혹고니"},
        "scientific_name": "Cygnus olor",
        "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200",
        "summary": {"en": "Large graceful waterfowl.", "zh": "体型大、姿态优雅的水禽。", "ko": "크고 우아한 물새."},
        "habitat": {"en": "Lakes and slow rivers", "zh": "湖泊与缓流水域", "ko": "호수·완만한 강"},
        "facts": {"en": ["Forms strong pair bonds."], "zh": ["配偶关系稳定。"], "ko": ["강한 짝 유대를 형성한다."]},
    },
    "crow": {
        "category": "birds",
        "name": {"en": "Carrion Crow", "zh": "小嘴乌鸦", "ko": "까마귀"},
        "scientific_name": "Corvus corone",
        "image": "https://images.unsplash.com/photo-1549608276-5786777e6587?w=1200",
        "summary": {"en": "Highly intelligent and adaptable.", "zh": "聪明且适应力强。", "ko": "지능이 높고 적응력이 뛰어나다."},
        "habitat": {"en": "Urban and rural areas", "zh": "城市与乡村", "ko": "도시·농촌"},
        "facts": {"en": ["Uses tools in some populations."], "zh": ["部分种群会使用工具。"], "ko": ["일부 집단은 도구를 사용한다."]},
    },
    "woodpecker": {
        "category": "birds",
        "name": {"en": "Great Spotted Woodpecker", "zh": "大斑啄木鸟", "ko": "큰오색딱따구리"},
        "scientific_name": "Dendrocopos major",
        "image": "https://images.unsplash.com/photo-1501706362039-c6e80948e1f8?w=1200",
        "summary": {"en": "Tree-drumming insect hunter.", "zh": "敲击树干捕食昆虫。", "ko": "나무를 두드려 곤충을 찾는다."},
        "habitat": {"en": "Woodlands", "zh": "林地", "ko": "수림"},
        "facts": {"en": ["Tongue is long and sticky."], "zh": ["舌头又长又黏。"], "ko": ["혀가 길고 끈적하다."]},
    },
    "ostrich": {
        "category": "birds",
        "name": {"en": "Ostrich", "zh": "鸵鸟", "ko": "타조"},
        "scientific_name": "Struthio camelus",
        "image": "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=1200",
        "summary": {"en": "Largest living bird, flightless but fast runner.", "zh": "现存最大鸟类，不能飞但跑得快。", "ko": "현존 최대 조류, 날지 못하지만 빠르게 달린다."},
        "habitat": {"en": "African savannas", "zh": "非洲草原", "ko": "아프리카 사바나"},
        "facts": {"en": ["Can sprint up to ~70 km/h."], "zh": ["短跑速度可接近70 km/h。"], "ko": ["시속 약 70km까지 달릴 수 있다."]},
    },

    # ===================== Reptiles (12) =====================
    "nile_crocodile": {
        "category": "reptiles",
        "name": {"en": "Nile Crocodile", "zh": "尼罗鳄", "ko": "나일악어"},
        "scientific_name": "Crocodylus niloticus",
        "image": "https://images.unsplash.com/photo-1535083783855-76ae62b2914e?w=1200",
        "summary": {"en": "Large African crocodile with powerful bite.", "zh": "非洲大型鳄鱼，咬合力惊人。", "ko": "강력한 턱을 가진 아프리카 대형 악어."},
        "habitat": {"en": "Rivers and lakes", "zh": "河流湖泊", "ko": "강·호수"},
        "facts": {"en": ["Can hold breath for long periods."], "zh": ["可长时间闭气。"], "ko": ["오랜 시간 숨을 참을 수 있다."]},
    },
    "komodo_dragon": {
        "category": "reptiles",
        "name": {"en": "Komodo Dragon", "zh": "科莫多巨蜥", "ko": "코모도왕도마뱀"},
        "scientific_name": "Varanus komodoensis",
        "image": "https://images.unsplash.com/photo-1594745561149-2211ca8c5d2c?w=1200",
        "summary": {"en": "The largest living lizard.", "zh": "现存体型最大的蜥蜴。", "ko": "현존 가장 큰 도마뱀."},
        "habitat": {"en": "Indonesian islands", "zh": "印度尼西亚岛屿", "ko": "인도네시아 섬"},
        "facts": {"en": ["Has a keen sense of smell."], "zh": ["嗅觉敏锐。"], "ko": ["후각이 예민하다."]},
    },
    "king_cobra": {
        "category": "reptiles",
        "name": {"en": "King Cobra", "zh": "眼镜王蛇", "ko": "킹코브라"},
        "scientific_name": "Ophiophagus hannah",
        "image": "https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=1200",
        "summary": {"en": "World's longest venomous snake.", "zh": "世界上最长的毒蛇。", "ko": "세계에서 가장 긴 독사."},
        "habitat": {"en": "Forests of South and Southeast Asia", "zh": "南亚与东南亚森林", "ko": "남·동남아 숲"},
        "facts": {"en": ["Preys on other snakes."], "zh": ["会捕食其他蛇类。"], "ko": ["다른 뱀을 잡아먹는다."]},
    },
    "green_iguana": {
        "category": "reptiles",
        "name": {"en": "Green Iguana", "zh": "绿鬣蜥", "ko": "초록이구아나"},
        "scientific_name": "Iguana iguana",
        "image": "https://images.unsplash.com/photo-1585095595205-97f2b0b6f2c3?w=1200",
        "summary": {"en": "Large arboreal lizard often herbivorous.", "zh": "树栖大型蜥蜴，多为草食。", "ko": "나무에 사는 큰 도마뱀, 주로 초식."},
        "habitat": {"en": "Tropical forests", "zh": "热带森林", "ko": "열대 숲"},
        "facts": {"en": ["Excellent climber and swimmer."], "zh": ["攀爬和游泳能力强。"], "ko": ["등반과 수영에 능하다."]},
    },
    "chameleon": {
        "category": "reptiles",
        "name": {"en": "Chameleon", "zh": "变色龙", "ko": "카멜레온"},
        "scientific_name": "Chamaeleonidae",
        "image": "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=1200",
        "summary": {"en": "Lizards known for color change and projectile tongues.", "zh": "以变色与弹射舌头闻名。", "ko": "색 변화와 탄환 같은 혀로 유명."},
        "habitat": {"en": "Forests and shrublands", "zh": "森林与灌丛", "ko": "숲·관목지"},
        "facts": {"en": ["Eyes can move independently."], "zh": ["双眼可独立转动。"], "ko": ["눈이 독립적으로 움직인다."]},
    },
    "sea_turtle": {
        "category": "reptiles",
        "name": {"en": "Green Sea Turtle", "zh": "绿海龟", "ko": "푸른바다거북"},
        "scientific_name": "Chelonia mydas",
        "image": "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1200",
        "summary": {"en": "A large marine turtle feeding mostly on seagrass.", "zh": "主要以海草为食的大型海龟。", "ko": "주로 해초를 먹는 대형 바다거북."},
        "habitat": {"en": "Tropical and subtropical seas", "zh": "热带/亚热带海域", "ko": "열대·아열대 해역"},
        "facts": {"en": ["Returns to natal beaches to nest."], "zh": ["会回到出生海滩产卵。"], "ko": ["태어난 해변으로 돌아가 산란한다."]},
    },
    "gecko": {
        "category": "reptiles",
        "name": {"en": "Tokay Gecko", "zh": "大守宫", "ko": "토케이게코"},
        "scientific_name": "Gekko gecko",
        "image": "https://images.unsplash.com/photo-1545243424-0ce743321e11?w=1200",
        "summary": {"en": "Noisy gecko with strong climbing pads.", "zh": "叫声响亮、吸盘强的壁虎。", "ko": "큰 소리와 강한 흡착 발바닥을 가진 도마뱀붙이."},
        "habitat": {"en": "Tropical Asia", "zh": "亚洲热带地区", "ko": "아시아 열대 지역"},
        "facts": {"en": ["Can climb smooth surfaces."], "zh": ["能爬光滑表面。"], "ko": ["매끈한 표면도 오른다."]},
    },
    "anaconda": {
        "category": "reptiles",
        "name": {"en": "Green Anaconda", "zh": "绿森蚺", "ko": "그린아나콘다"},
        "scientific_name": "Eunectes murinus",
        "image": "https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=1200",
        "summary": {"en": "One of the heaviest snakes, semi-aquatic.", "zh": "体重最大的蛇之一，半水栖。", "ko": "가장 무거운 뱀 중 하나로 반수생."},
        "habitat": {"en": "Amazon wetlands", "zh": "亚马孙湿地", "ko": "아마존 습지"},
        "facts": {"en": ["Kills prey by constriction."], "zh": ["用缠绕压制猎物。"], "ko": ["몸을 감아 먹이를 제압한다."]},
    },
    "python": {
        "category": "reptiles",
        "name": {"en": "Burmese Python", "zh": "缅甸蟒", "ko": "버마비단뱀"},
        "scientific_name": "Python bivittatus",
        "image": "https://images.unsplash.com/photo-1519817650390-64a93db511aa?w=1200",
        "summary": {"en": "Large constrictor native to Southeast Asia.", "zh": "东南亚原产大型蟒蛇。", "ko": "동남아 원산의 대형 비단뱀."},
        "habitat": {"en": "Forests and swamps", "zh": "森林与沼泽", "ko": "숲·습지"},
        "facts": {"en": ["Excellent swimmer."], "zh": ["游泳能力强。"], "ko": ["수영을 잘한다."]},
    },
    "rattlesnake": {
        "category": "reptiles",
        "name": {"en": "Rattlesnake", "zh": "响尾蛇", "ko": "방울뱀"},
        "scientific_name": "Crotalus spp.",
        "image": "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=1200",
        "summary": {"en": "Venomous snakes with a warning rattle.", "zh": "尾端有警戒性响声的毒蛇。", "ko": "경고용 방울을 가진 독사."},
        "habitat": {"en": "Americas' dry regions", "zh": "美洲干旱地区", "ko": "아메리카 건조 지역"},
        "facts": {"en": ["Rattle warns threats to back off."], "zh": ["响声用于警告。"], "ko": ["방울 소리로 경고한다."]},
    },
    "alligator": {
        "category": "reptiles",
        "name": {"en": "American Alligator", "zh": "美洲短吻鳄", "ko": "아메리카악어"},
        "scientific_name": "Alligator mississippiensis",
        "image": "https://images.unsplash.com/photo-1528150177508-7cc0c36cda5c?w=1200",
        "summary": {"en": "Large reptile of southeastern US wetlands.", "zh": "美国东南部湿地大型鳄类。", "ko": "미국 남동부 습지의 대형 파충류."},
        "habitat": {"en": "Freshwater wetlands", "zh": "淡水湿地", "ko": "담수 습지"},
        "facts": {"en": ["Builds 'gator holes' that help ecosystems."], "zh": ["“鳄鱼洞”有助生态系统。"], "ko": ["'악어 구덩이'가 생태계에 도움을 준다."]},
    },
    "gila_monster": {
        "category": "reptiles",
        "name": {"en": "Gila Monster", "zh": "吉拉毒蜥", "ko": "길라몬스터"},
        "scientific_name": "Heloderma suspectum",
        "image": "https://images.unsplash.com/photo-1585095595205-97f2b0b6f2c3?w=1200",
        "summary": {"en": "One of the few venomous lizards.", "zh": "少数有毒蜥蜴之一。", "ko": "몇 안 되는 독도마뱀."},
        "habitat": {"en": "Deserts of southwestern US", "zh": "美国西南沙漠", "ko": "미국 남서부 사막"},
        "facts": {"en": ["Stores fat in its tail."], "zh": ["尾部储存脂肪。"], "ko": ["꼬리에 지방을 저장한다."]},
    },

    # ===================== Amphibians (12) =====================
    "red_eyed_tree_frog": {
        "category": "amphibians",
        "name": {"en": "Red-eyed Tree Frog", "zh": "红眼树蛙", "ko": "붉은눈청개구리"},
        "scientific_name": "Agalychnis callidryas",
        "image": "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=1200",
        "summary": {"en": "Bright rainforest frog with striking red eyes.", "zh": "热带雨林的鲜艳树蛙。", "ko": "강렬한 붉은 눈을 가진 열대우림 개구리."},
        "habitat": {"en": "Central American rainforests", "zh": "中美洲雨林", "ko": "중미 열대우림"},
        "facts": {"en": ["Nocturnal and arboreal."], "zh": ["夜行性、树栖。"], "ko": ["야행성이며 나무에서 산다."]},
    },
    "axolotl": {
        "category": "amphibians",
        "name": {"en": "Axolotl", "zh": "墨西哥钝口螈", "ko": "아홀로틀"},
        "scientific_name": "Ambystoma mexicanum",
        "image": "https://images.unsplash.com/photo-1610465299993-8d3f8d16f5f7?w=1200",
        "summary": {"en": "Neotenic salamander famous for regeneration.", "zh": "以再生能力著称的幼态蝾螈。", "ko": "재생 능력으로 유명한 네오테니 도롱뇽."},
        "habitat": {"en": "Lakes near Mexico City", "zh": "墨西哥城附近湖泊", "ko": "멕시코시티 인근 호수"},
        "facts": {"en": ["Can regrow limbs."], "zh": ["可再生肢体。"], "ko": ["팔다리를 재생한다."]},
    },
    "poison_dart_frog": {
        "category": "amphibians",
        "name": {"en": "Poison Dart Frog", "zh": "箭毒蛙", "ko": "독화살개구리"},
        "scientific_name": "Dendrobatidae",
        "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200",
        "summary": {"en": "Small colorful frogs with potent toxins.", "zh": "色彩艳丽、毒性强的小型蛙类。", "ko": "강한 독을 가진 작고 화려한 개구리."},
        "habitat": {"en": "South American rainforests", "zh": "南美雨林", "ko": "남미 열대우림"},
        "facts": {"en": ["Toxins come from diet."], "zh": ["毒素多来自食物链。"], "ko": ["독은 먹이에서 유래한다."]},
    },
    "bullfrog": {
        "category": "amphibians",
        "name": {"en": "American Bullfrog", "zh": "美洲牛蛙", "ko": "황소개구리"},
        "scientific_name": "Lithobates catesbeianus",
        "image": "https://images.unsplash.com/photo-1501706362039-c6e80948e1f8?w=1200",
        "summary": {"en": "Large frog with deep booming calls.", "zh": "体型大、叫声低沉。", "ko": "큰 체구와 깊은 울음소리."},
        "habitat": {"en": "Ponds and lakes", "zh": "池塘湖泊", "ko": "연못·호수"},
        "facts": {"en": ["An opportunistic predator."], "zh": ["机会主义捕食者。"], "ko": ["기회주의적 포식자."]},
    },
    "common_toad": {
        "category": "amphibians",
        "name": {"en": "Common Toad", "zh": "普通蟾蜍", "ko": "두꺼비"},
        "scientific_name": "Bufo bufo",
        "image": "https://images.unsplash.com/photo-1528150177508-7cc0c36cda5c?w=1200",
        "summary": {"en": "Warty toad common across Europe.", "zh": "欧洲常见的疣皮蟾蜍。", "ko": "유럽에 흔한 사마귀 피부 두꺼비."},
        "habitat": {"en": "Woodlands and gardens", "zh": "林地与花园", "ko": "숲·정원"},
        "facts": {"en": ["Has poison glands behind eyes."], "zh": ["眼后有毒腺。"], "ko": ["눈 뒤에 독샘이 있다."]},
    },
    "salamander": {
        "category": "amphibians",
        "name": {"en": "Fire Salamander", "zh": "火蝾螈", "ko": "불도롱뇽"},
        "scientific_name": "Salamandra salamandra",
        "image": "https://images.unsplash.com/photo-1585095595205-97f2b0b6f2c3?w=1200",
        "summary": {"en": "Black-and-yellow salamander secreting toxins.", "zh": "黑黄相间、会分泌毒素。", "ko": "검정-노랑 무늬로 독성 분비."},
        "habitat": {"en": "Moist forests", "zh": "潮湿森林", "ko": "습한 숲"},
        "facts": {"en": ["Warns predators with bright colors."], "zh": ["警戒色防御。"], "ko": ["경고색으로 방어한다."]},
    },
    "newt": {
        "category": "amphibians",
        "name": {"en": "Smooth Newt", "zh": "光滑蝾螈", "ko": "민도롱뇽"},
        "scientific_name": "Lissotriton vulgaris",
        "image": "https://images.unsplash.com/photo-1611689342806-0863700ce1e4?w=1200",
        "summary": {"en": "Small newt with aquatic breeding phase.", "zh": "繁殖期多水栖的小型蝾螈。", "ko": "번식기에 수중 생활을 하는 작은 뉴트."},
        "habitat": {"en": "Ponds and woodlands", "zh": "池塘与林地", "ko": "연못·수림"},
        "facts": {"en": ["Males develop crests in breeding season."], "zh": ["雄性繁殖期会长背脊。"], "ko": ["번식기에 수컷이 볏을 발달시킨다."]},
    },
    "glass_frog": {
        "category": "amphibians",
        "name": {"en": "Glass Frog", "zh": "玻璃蛙", "ko": "유리개구리"},
        "scientific_name": "Centrolenidae",
        "image": "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=1200",
        "summary": {"en": "Frogs with translucent bellies.", "zh": "腹部半透明的奇特蛙类。", "ko": "배가 반투명한 개구리."},
        "habitat": {"en": "Cloud forests", "zh": "云雾林", "ko": "운무림"},
        "facts": {"en": ["Often guard eggs on leaves."], "zh": ["常在叶片上护卵。"], "ko": ["잎 위의 알을 지키는 경우가 많다."]},
    },
    "mudpuppy": {
        "category": "amphibians",
        "name": {"en": "Mudpuppy", "zh": "泥狗蝾螈", "ko": "머드퍼피"},
        "scientific_name": "Necturus maculosus",
        "image": "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=1200",
        "summary": {"en": "Fully aquatic salamander with external gills.", "zh": "终生水栖、外鳃明显。", "ko": "평생 수중에서 살며 외부 아가미가 있다."},
        "habitat": {"en": "North American lakes", "zh": "北美湖泊", "ko": "북미 호수"},
        "facts": {"en": ["Active mainly at night."], "zh": ["多夜间活动。"], "ko": ["주로 야간 활동."]},
    },
    "spadefoot_toad": {
        "category": "amphibians",
        "name": {"en": "Spadefoot Toad", "zh": "铲足蟾", "ko": "삽발두꺼비"},
        "scientific_name": "Scaphiopodidae",
        "image": "https://images.unsplash.com/photo-1528150177508-7cc0c36cda5c?w=1200",
        "summary": {"en": "Burrowing toads adapted to dry habitats.", "zh": "适应干旱、善挖掘。", "ko": "건조 환경에 적응한 굴파는 두꺼비."},
        "habitat": {"en": "Semi-arid regions", "zh": "半干旱地区", "ko": "반건조 지역"},
        "facts": {"en": ["Can stay underground for long time."], "zh": ["可长期潜伏地下。"], "ko": ["오랫동안 땅속에 머문다."]},
    },
    "caecilian": {
        "category": "amphibians",
        "name": {"en": "Caecilian", "zh": "蚓螈", "ko": "무족양서류"},
        "scientific_name": "Gymnophiona",
        "image": "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=1200",
        "summary": {"en": "Legless burrowing amphibians.", "zh": "无足、地下生活的两栖类。", "ko": "다리가 없는 굴파는 양서류."},
        "habitat": {"en": "Tropical soils", "zh": "热带土壤层", "ko": "열대 토양"},
        "facts": {"en": ["Often mistaken for worms or snakes."], "zh": ["常被误认为蚯蚓或蛇。"], "ko": ["지렁이나 뱀으로 오해받기도 한다."]},
    },
    "leopard_frog": {
        "category": "amphibians",
        "name": {"en": "Leopard Frog", "zh": "豹纹蛙", "ko": "표범개구리"},
        "scientific_name": "Lithobates pipiens",
        "image": "https://images.unsplash.com/photo-1501706362039-c6e80948e1f8?w=1200",
        "summary": {"en": "Spotted frog common in North America.", "zh": "北美常见斑点蛙。", "ko": "북미에 흔한 점무늬 개구리."},
        "habitat": {"en": "Marshes and ponds", "zh": "沼泽与池塘", "ko": "습지·연못"},
        "facts": {"en": ["Powerful jumper."], "zh": ["跳跃能力强。"], "ko": ["점프력이 좋다."]},
    },

    # ===================== Fish (12) =====================
    "great_white_shark": {
        "category": "fish",
        "name": {"en": "Great White Shark", "zh": "大白鲨", "ko": "백상아리"},
        "scientific_name": "Carcharodon carcharias",
        "image": "https://images.unsplash.com/photo-1560275619-4662e36fa65c?w=1200",
        "summary": {"en": "Apex predator of temperate oceans.", "zh": "温带海域顶级掠食者。", "ko": "온대 해역의 최상위 포식자."},
        "habitat": {"en": "Coastal and open ocean", "zh": "近海与外海", "ko": "연안·원양"},
        "facts": {"en": ["Highly sensitive to electromagnetic fields."], "zh": ["能感知微弱电场。"], "ko": ["미약한 전자기장을 감지한다."]},
    },
    "clownfish": {
        "category": "fish",
        "name": {"en": "Clownfish", "zh": "小丑鱼", "ko": "흰동가리"},
        "scientific_name": "Amphiprioninae",
        "image": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200",
        "summary": {"en": "Reef fish living symbiotically with sea anemones.", "zh": "与海葵共生的珊瑚礁鱼类。", "ko": "말미잘과 공생하는 산호초 물고기."},
        "habitat": {"en": "Coral reefs", "zh": "珊瑚礁", "ko": "산호초"},
        "facts": {"en": ["All are born male; some change to female."], "zh": ["先雄后雌。"], "ko": ["처음엔 수컷으로 태어나 일부가 암컷으로 전환."]},
    },
    "blue_tang": {
        "category": "fish",
        "name": {"en": "Blue Tang", "zh": "蓝倒吊", "ko": "블루탱"},
        "scientific_name": "Paracanthurus hepatus",
        "image": "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=1200",
        "summary": {"en": "Bright blue reef fish with sharp tail spines.", "zh": "尾柄有锋利棘的蓝色礁鱼。", "ko": "꼬리 가시에 날카로운 구조가 있는 푸른 산호초 어류."},
        "habitat": {"en": "Indo-Pacific reefs", "zh": "印太珊瑚礁", "ko": "인도-태평양 산호초"},
        "facts": {"en": ["Uses tail spine for defense."], "zh": ["用尾棘防御。"], "ko": ["꼬리 가시로 방어."]},
    },
    "salmon": {
        "category": "fish",
        "name": {"en": "Atlantic Salmon", "zh": "大西洋鲑", "ko": "대서양연어"},
        "scientific_name": "Salmo salar",
        "image": "https://images.unsplash.com/photo-1543872084-c7bd3822856d?w=1200",
        "summary": {"en": "Migratory fish returning to rivers to spawn.", "zh": "洄游回河产卵的鱼类。", "ko": "산란을 위해 강으로 돌아오는 회유성 어류."},
        "habitat": {"en": "Ocean and freshwater rivers", "zh": "海洋与淡水河流", "ko": "바다·강"},
        "facts": {"en": ["Navigates using smell."], "zh": ["依靠嗅觉导航。"], "ko": ["후각으로 길을 찾는다."]},
    },
    "tuna": {
        "category": "fish",
        "name": {"en": "Bluefin Tuna", "zh": "蓝鳍金枪鱼", "ko": "참다랑어"},
        "scientific_name": "Thunnus thynnus",
        "image": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200",
        "summary": {"en": "Fast ocean swimmer with partial warm-blooded traits.", "zh": "游速极快，具部分温血特性。", "ko": "빠른 속도로 헤엄치며 부분적 온혈 특성이 있다."},
        "habitat": {"en": "Open oceans", "zh": "大洋", "ko": "대양"},
        "facts": {"en": ["Can cross entire oceans."], "zh": ["可跨洋迁徙。"], "ko": ["대양을 횡단할 수 있다."]},
    },
    "seahorse": {
        "category": "fish",
        "name": {"en": "Seahorse", "zh": "海马", "ko": "해마"},
        "scientific_name": "Hippocampus",
        "image": "https://images.unsplash.com/photo-1516683037151-9a17603a8dc7?w=1200",
        "summary": {"en": "Unique fish where males carry pregnancies.", "zh": "雄性“怀孕”的独特鱼类。", "ko": "수컷이 임신을 담당하는 독특한 물고기."},
        "habitat": {"en": "Seagrass beds", "zh": "海草床", "ko": "해초 군락"},
        "facts": {"en": ["Male broods young in a pouch."], "zh": ["雄性育儿袋孵育。"], "ko": ["수컷이 육아낭에서 새끼를 기른다."]},
    },
    "ray": {
        "category": "fish",
        "name": {"en": "Manta Ray", "zh": "蝠鲼", "ko": "만타가오리"},
        "scientific_name": "Mobula birostris",
        "image": "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=1200",
        "summary": {"en": "Giant filter-feeding ray.", "zh": "大型滤食性鳐鱼。", "ko": "거대한 여과섭식 가오리."},
        "habitat": {"en": "Tropical seas", "zh": "热带海域", "ko": "열대 해역"},
        "facts": {"en": ["Can leap out of water."], "zh": ["可跃出水面。"], "ko": ["물 밖으로 점프하기도 한다."]},
    },
    "eel": {
        "category": "fish",
        "name": {"en": "Moray Eel", "zh": "海鳝", "ko": "곰치"},
        "scientific_name": "Muraenidae",
        "image": "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=1200",
        "summary": {"en": "Reef-dwelling eel with powerful jaws.", "zh": "生活在珊瑚礁、颌部强壮。", "ko": "산호초에 사는 강력한 턱의 장어."},
        "habitat": {"en": "Coral crevices", "zh": "礁石缝隙", "ko": "산호 틈"},
        "facts": {"en": ["Has a second set of pharyngeal jaws."], "zh": ["有“咽颌”。"], "ko": ["‘인두 턱’이 있다."]},
    },
    "carp": {
        "category": "fish",
        "name": {"en": "Common Carp", "zh": "鲤鱼", "ko": "잉어"},
        "scientific_name": "Cyprinus carpio",
        "image": "https://images.unsplash.com/photo-1543872084-c7bd3822856d?w=1200",
        "summary": {"en": "Hardy freshwater fish widely domesticated.", "zh": "适应力强的淡水鱼。", "ko": "적응력이 강한 담수어."},
        "habitat": {"en": "Rivers and lakes", "zh": "河流湖泊", "ko": "강·호수"},
        "facts": {"en": ["Can live in low-oxygen water."], "zh": ["耐低氧。"], "ko": ["저산소 환경에서도 버틴다."]},
    },
    "pufferfish": {
        "category": "fish",
        "name": {"en": "Pufferfish", "zh": "河豚", "ko": "복어"},
        "scientific_name": "Tetraodontidae",
        "image": "https://images.unsplash.com/photo-1516683037151-9a17603a8dc7?w=1200",
        "summary": {"en": "Inflates for defense; some contain potent toxins.", "zh": "可膨胀防御，部分含强毒素。", "ko": "부풀어 방어하며 일부는 강한 독을 지닌다."},
        "habitat": {"en": "Tropical seas and estuaries", "zh": "热带海域与河口", "ko": "열대 해역·하구"},
        "facts": {"en": ["Tetrodotoxin can be lethal."], "zh": ["河豚毒素可致命。"], "ko": ["테트로도톡신은 치명적일 수 있다."]},
    },
    "angelfish": {
        "category": "fish",
        "name": {"en": "Emperor Angelfish", "zh": "皇帝神仙鱼", "ko": "황제엔젤피시"},
        "scientific_name": "Pomacanthus imperator",
        "image": "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=1200",
        "summary": {"en": "Colorful Indo-Pacific reef fish.", "zh": "印太地区色彩绚丽的礁鱼。", "ko": "인도-태평양의 화려한 산호초 어류."},
        "habitat": {"en": "Coral reefs", "zh": "珊瑚礁", "ko": "산호초"},
        "facts": {"en": ["Juveniles look very different from adults."], "zh": ["幼体与成体花纹差异大。"], "ko": ["유체와 성체 무늬가 크게 다르다."]},
    },
    "arowana": {
        "category": "fish",
        "name": {"en": "Arowana", "zh": "龙鱼", "ko": "아로와나"},
        "scientific_name": "Osteoglossidae",
        "image": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200",
        "summary": {"en": "Surface-hunting fish famous in aquariums.", "zh": "水面捕食、观赏价值高。", "ko": "수면에서 사냥하며 관상어로 유명."},
        "habitat": {"en": "Slow tropical rivers", "zh": "热带缓流河", "ko": "열대 완만한 강"},
        "facts": {"en": ["Can jump to catch insects."], "zh": ["会跳出水面捕食昆虫。"], "ko": ["물 밖으로 뛰어 곤충을 잡기도 한다."]},
    },

    # ===================== Insects (12) =====================
    "monarch_butterfly": {
        "category": "insects",
        "name": {"en": "Monarch Butterfly", "zh": "帝王蝶", "ko": "왕나비"},
        "scientific_name": "Danaus plexippus",
        "image": "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=1200",
        "summary": {"en": "Famous for long-distance migration.", "zh": "以长距离迁徙闻名。", "ko": "장거리 이동으로 유명."},
        "habitat": {"en": "Meadows and gardens", "zh": "草地与花园", "ko": "초지·정원"},
        "facts": {"en": ["Migrates across North America."], "zh": ["跨越北美迁徙。"], "ko": ["북미를 가로질러 이동한다."]},
    },
    "honeybee": {
        "category": "insects",
        "name": {"en": "Honey Bee", "zh": "蜜蜂", "ko": "꿀벌"},
        "scientific_name": "Apis mellifera",
        "image": "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=1200",
        "summary": {"en": "Key pollinator with complex social colonies.", "zh": "重要传粉昆虫，社会结构复杂。", "ko": "중요한 수분 매개 곤충, 복잡한 사회 구조."},
        "habitat": {"en": "Fields and orchards", "zh": "田野与果园", "ko": "들·과수원"},
        "facts": {"en": ["Communicates via 'waggle dance'."], "zh": ["用“8字舞”交流。"], "ko": ["‘8자 춤’으로 의사소통한다."]},
    },
    "ladybug": {
        "category": "insects",
        "name": {"en": "Ladybug", "zh": "瓢虫", "ko": "무당벌레"},
        "scientific_name": "Coccinellidae",
        "image": "https://images.unsplash.com/photo-1501706362039-c6e80948e1f8?w=1200",
        "summary": {"en": "Small beetles that often eat aphids.", "zh": "常捕食蚜虫的益虫。", "ko": "진딧물을 먹는 유익한 딱정벌레."},
        "habitat": {"en": "Gardens", "zh": "花园与农田", "ko": "정원·농지"},
        "facts": {"en": ["Helpful for natural pest control."], "zh": ["天然生物防治帮手。"], "ko": ["자연 해충 방제에 도움."]},
    },
    "dragonfly": {
        "category": "insects",
        "name": {"en": "Dragonfly", "zh": "蜻蜓", "ko": "잠자리"},
        "scientific_name": "Odonata",
        "image": "https://images.unsplash.com/photo-1465101162946-4377e57745c3?w=1200",
        "summary": {"en": "Agile aerial predators near water.", "zh": "水边敏捷的空中捕食者。", "ko": "물가의 민첩한 공중 포식자."},
        "habitat": {"en": "Wetlands", "zh": "湿地与水域周边", "ko": "습지"},
        "facts": {"en": ["Nymphs live underwater."], "zh": ["若虫水生。"], "ko": ["유충은 물속에서 산다."]},
    },
    "praying_mantis": {
        "category": "insects",
        "name": {"en": "Praying Mantis", "zh": "螳螂", "ko": "사마귀"},
        "scientific_name": "Mantodea",
        "image": "https://images.unsplash.com/photo-1585095595205-97f2b0b6f2c3?w=1200",
        "summary": {"en": "Ambush predator with raptorial forelegs.", "zh": "有镰刀状前足的伏击捕食者。", "ko": "낫 모양 앞다리로 매복 사냥."},
        "habitat": {"en": "Shrublands and gardens", "zh": "灌丛与花园", "ko": "관목지·정원"},
        "facts": {"en": ["Excellent camouflage."], "zh": ["拟态能力强。"], "ko": ["위장 능력이 뛰어나다."]},
    },
    "ant": {
        "category": "insects",
        "name": {"en": "Ant", "zh": "蚂蚁", "ko": "개미"},
        "scientific_name": "Formicidae",
        "image": "https://images.unsplash.com/photo-1549608276-5786777e6587?w=1200",
        "summary": {"en": "Social insects building complex colonies.", "zh": "社会性极强的昆虫。", "ko": "복잡한 군체를 이루는 사회성 곤충."},
        "habitat": {"en": "Worldwide", "zh": "全球广泛分布", "ko": "전 세계"},
        "facts": {"en": ["Can carry many times their body weight."], "zh": ["可搬运远超体重的物体。"], "ko": ["체중의 여러 배를 운반한다."]},
    },
    "termite": {
        "category": "insects",
        "name": {"en": "Termite", "zh": "白蚁", "ko": "흰개미"},
        "scientific_name": "Isoptera",
        "image": "https://images.unsplash.com/photo-1543872084-c7bd3822856d?w=1200",
        "summary": {"en": "Wood-eating social insects important for decomposition.", "zh": "取食木质、重要分解者。", "ko": "목재를 먹는 사회성 곤충, 분해에 중요."},
        "habitat": {"en": "Tropical and temperate regions", "zh": "热带与温带", "ko": "열대·온대"},
        "facts": {"en": ["Builds elaborate mounds."], "zh": ["会建造复杂蚁丘。"], "ko": ["정교한 흙집을 만든다."]},
    },
    "grasshopper": {
        "category": "insects",
        "name": {"en": "Grasshopper", "zh": "蝗虫/蚱蜢", "ko": "메뚜기"},
        "scientific_name": "Caelifera",
        "image": "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=1200",
        "summary": {"en": "Jumping herbivorous insects.", "zh": "善跳跃的植食性昆虫。", "ko": "뛰기에 능한 초식 곤충."},
        "habitat": {"en": "Grasslands", "zh": "草地与农田", "ko": "초원·농지"},
        "facts": {"en": ["Some species form destructive swarms."], "zh": ["部分会形成蝗灾群。"], "ko": ["일부 종은 대군집을 이룬다."]},
    },
    "stag_beetle": {
        "category": "insects",
        "name": {"en": "Stag Beetle", "zh": "锹形虫", "ko": "사슴벌레"},
        "scientific_name": "Lucanidae",
        "image": "https://images.unsplash.com/photo-1545243424-0ce743321e11?w=1200",
        "summary": {"en": "Beetles with enlarged mandibles in males.", "zh": "雄虫有巨大的大颚。", "ko": "수컷의 큰 턱이 특징."},
        "habitat": {"en": "Forests", "zh": "森林", "ko": "숲"},
        "facts": {"en": ["Larvae feed on decaying wood."], "zh": ["幼虫取食腐木。"], "ko": ["유충은 썩은 나무를 먹는다."]},
    },
    "firefly": {
        "category": "insects",
        "name": {"en": "Firefly", "zh": "萤火虫", "ko": "반딧불이"},
        "scientific_name": "Lampyridae",
        "image": "https://images.unsplash.com/photo-1452570053594-1b985d6ea890?w=1200",
        "summary": {"en": "Bioluminescent beetles used in mating signals.", "zh": "会发光的甲虫。", "ko": "생물발광을 하는 딱정벌레."},
        "habitat": {"en": "Moist areas", "zh": "潮湿环境", "ko": "습한 지역"},
        "facts": {"en": ["Light patterns are species-specific."], "zh": ["闪光模式因种而异。"], "ko": ["발광 패턴이 종마다 다르다."]},
    },
    "mosquito": {
        "category": "insects",
        "name": {"en": "Mosquito", "zh": "蚊子", "ko": "모기"},
        "scientific_name": "Culicidae",
        "image": "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=1200",
        "summary": {"en": "Widespread insects; some species transmit diseases.", "zh": "部分种类可传播疾病。", "ko": "일부 종은 질병을 매개한다."},
        "habitat": {"en": "Near standing water", "zh": "积水附近", "ko": "고인 물 주변"},
        "facts": {"en": ["Only females bite for blood."], "zh": ["通常雌蚊吸血。"], "ko": ["대부분 암컷만 흡혈."]},
    },
    "cicada": {
        "category": "insects",
        "name": {"en": "Cicada", "zh": "蝉", "ko": "매미"},
        "scientific_name": "Cicadidae",
        "image": "https://images.unsplash.com/photo-1549608276-5786777e6587?w=1200",
        "summary": {"en": "Known for loud summer calls.", "zh": "以夏季鸣叫著称。", "ko": "여름의 큰 울음소리로 유명."},
        "habitat": {"en": "Woodlands", "zh": "林地", "ko": "수림"},
        "facts": {"en": ["Some have multi-year underground nymph stages."], "zh": ["若虫可多年地下生活。"], "ko": ["유충이 수년간 지하에서 산다."]},
    },
    "wasp": {
        "category": "insects",
        "name": {"en": "Wasp", "zh": "黄蜂/胡蜂", "ko": "말벌/벌"},
        "scientific_name": "Vespidae",
        "image": "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=1200",
        "summary": {"en": "Predatory and social in many species.", "zh": "很多种类具社会性与捕食性。", "ko": "많은 종이 사회성이 있고 포식한다."},
        "habitat": {"en": "Forests and urban areas", "zh": "森林与城市", "ko": "숲·도시"},
        "facts": {"en": ["Helps control pest insects."], "zh": ["可控制害虫数量。"], "ko": ["해충 조절에 기여한다."]},
    },

    # ===================== (补齐) Mammals/Birds/Reptiles/Amphibians/Fish/Insects 已达到 12 =====================
    # 为了保持文件不爆炸：下面不再额外加长文本
}

def get_animals_by_category(category_id):
    return {aid: a for aid, a in ANIMALS_DATA.items() if a["category"] == category_id}

def get_animal_detail(animal_id):
    return ANIMALS_DATA.get(animal_id)
